config/routes.rb
Rails.application.routes.draw do
  
  root "pages#home"
  get 'pages/home', to: 'pages#home'
   get '/about', to: 'pages#about'
   
   resources :recipes do
     resources :comments, only: [:create]
     member do
      post 'like'
     end
   end
   
   get'/signup', to: 'chefs#new'
   resources :chefs, except: [:new]
   
   get '/login', to: 'sessions#new'
   post '/login', to: "sessions#create"
   delete '/logout', to: "sessions#destroy"
   
   resources :ingredients, except: [:destroy]
   
    mount ActionCable.server => 'cable'
   
   get '/chat', to: 'chatrooms#show'
   
   resources :messages, only: [:create]
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  
  belongs_to :chef
  
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 5, maximum: 500 }
  validates :chef_id, presence: true
  default_scope -> { order(updated_at: :desc) }
  
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  
  def thumbs_up_total
    self.likes.where(like: true).size
  end
  
  def thumbs_down_total
    self.likes.where(like: false).size
  end
  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy, :like]
  before_action :require_user, except: [:index, :show, :like]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_user_like, only: [:like]
  
  def index 
    @recipes = Recipe.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def show
    @comment = Comment.new
    @comments = @recipe.comments.paginate(page: params[:page], per_page: 5)
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = current_chef
    if @recipe.save
      flash[:success] = "Recipe was created successfully!"
      redirect_to recipe_path(@recipe)
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @recipe.update(recipe_params)
      flash[:warning] = "Recipe was updated successfully!"
      redirect_to recipe_path(@recipe)
    else
      render 'edit'
    end
  end
  
  def destroy
    Recipe.find(params[:id]).destroy
    flash[:danger] = "Recipe deleted successfully"
    redirect_to recipes_path
  end
  
  def like
    like = Like.create(like: params[:like], chef: current_chef, recipe: @recipe)
    if like.valid?
      flash[:success] = "Your selection was successful"
      redirect_to recipes_path
    else
      flash[:danger] = "You can only like/dislike a recipe once"
      redirect_to recipes_path
    end
  end
  
  private
  
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end
  
    def recipe_params
      params.require(:recipe).permit(:name, :description, ingredient_ids:[])
    end
    
    def require_same_user
      if current_chef != @recipe.chef and !current_chef.admin?
        flash[:danger] = "You can only edit or delete your own recipes"
        redirect_to recipes_path
      end
    end
    
    def require_user_like
      if !logged_in?
        flash[:danger] = "You must be logged in to perform that action"
        redirect_to :back
      end
    end
end

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class='container'>
<div class='row justify-content-start'>
   <div class='w-100'>
    <%= form_for(@recipe, :html => {class: 'form-group', role: 'form' }) do |f| %>
    <div class='form-group row'>
      <div class='form-control-label col-2'>
        <%= f.label :name %>
      </div>
      <div class='col-10'>
        <%= f.text_field :name, class: 'form-control border border-info', 
                             placeholder: 'Name of recipe', autofocus: true %>
      </div>
    </div>
    <div class='form-group row'>
      <div class='form-control-label col-2'>
        <%= f.label :description %>
      </div>
      <div class='col-10'>
        <%= f.text_area :description, rows: 10, class: 'form-control border border-info',
                         placeholder: 'Enter steps to create recipe' %>
      </div>
    </div>
    <div class='form-group row'>
      <div class='col-8'>
        <div class="input-group">
        <%= f.collection_check_boxes :ingredient_ids,
                           Ingredient.all, :id, :name do |cb| %>
        <% cb.label(class: "input-group-addon input_checkbox") { cb.check_box(class: "checkbox") + cb.text } %>
        <% end %>
      </div>
      </div>
    </div>
    <div class='form-group'>
      <div class='col-10 offset-2'>
          <%= f.submit class: 'btn btn-primary btn-sm btn-xlarge' %>
      </div>
    </div>
    <% end %>
  </div>
</div>
    <div class='col-10 offset-2 colormatch'>
      [<%= link_to 'Cancel', recipes_path %>]
    </div>
  </div>
</div>
</div>

app/views/recipes/_recipe.html.erb
<div class='container'>
  <% obj.each do |recipe| %>
    <div class='row'>
      <div class='col-2'>
        <!--<section class='chef_info center'>-->
        <!--  <#%= gravatar_for(recipe.chef, size: 120) %>-->
        <!--</section>-->
      </div>
        <div class="col d-flex justify-content-center card border-info mb-3">
        <div class='justify-content-md-center card-body colormatch'>
          <h4><%= link_to recipe.name.capitalize, recipe_path(recipe) %></h4>
          <p><%= truncate(recipe.description, length: 150) %></p>
            <% if recipe.ingredients.any? %>
              <p>Ingredients: <%= render recipe.ingredients %></p>
            <% end %>
          <p>
            <span class='quiet'>
              <small>Created 
                <%= time_ago_in_words(recipe.created_at) %> ago by
                <%= recipe.chef.chefname.capitalize %> |
                <%= pluralize(recipe.comments.count, 'Comment') %>
              </small>
            </span>
          </p>
          <% if logged_in? && (current_chef == recipe.chef || current_chef.admin?) %>
          <div class='recipe-actions'>
            <%= link_to "Edit this recipe", edit_recipe_path(recipe), 
                      class: 'badge badge-pill badge-warning' %>
            <%= link_to "Delete this recipe", recipe_path(recipe), method: :delete,
                    data: { confirm: "Are you sure you want to delete this recipe?" },
                    class: "badge badge-pill badge-danger" %>
          </div>
          <% end %>
          <div class="col-2 ml-auto">
            <div class="liking">
              <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
                <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
              <% end %><%= recipe.thumbs_up_total %> ||
              <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
                 <i class="fa fa-thumbs-down" aria-hidden="true"></i>
              <% end %><%= recipe.thumbs_down_total %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: 'edit an existing recipe' %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "showing all recipes" %>

<div class="pagination justify-content-center apple_pagination">
  <%= will_paginate %>
</div>

<%= render 'recipe', obj: @recipes %>

<div class="pagination justify-content-center apple_pagination">
  <%= will_paginate %>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: 'create a new recipe' %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>

<div class='container'>
    <div class='row'>
      <div class='col-2'>
        <section class='chef_info center'>
          <%= link_to gravatar_for(@recipe.chef), chef_path(@recipe.chef) %>
        </section>
      </div>
        <div class="col d-flex justify-content-center card border-info mb-3">
        <div class='justify-content-md-center card-body colormatch'>
          <h4 class='text-center description'><strong>Directions: </strong></h4>
            <%= simple_format(@recipe.description) %>
            <% if @recipe.ingredients.any? %>
              <p>Ingredients: <%= render @recipe.ingredients %></p>
            <% end %>
          <p>
            <span class='quiet'>
              <small>Created <%= time_ago_in_words(@recipe.created_at) %> ago by
               <%= @recipe.chef.chefname.capitalize %></small>
            </span>
          </p>
          <% if logged_in? && (current_chef == @recipe.chef || current_chef.admin?) %>
            <div class='recipe-actions'>
              <%= link_to "Edit this recipe", edit_recipe_path(@recipe), 
                        class: 'badge badge-pill badge-warning' %>
              <%= link_to "Delete this recipe", recipe_path(@recipe), method: :delete,
                      data: { confirm: "Are you sure you want to delete this recipe?" },
                      class: "badge badge-pill badge-danger" %>
          <% end %>
             <%= link_to "Back to all Recipes", recipes_path, class: "badge badge-pill badge-info" %>
            </div>
            <div class="row liking">
              <div class="pl-3 row col-8">
                <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
                  <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
                <% end %> <%= @recipe.thumbs_up_total %> ||
                <%= link_to like_recipe_path(@recip, like: false), method: :post do %>
                  <i class="fa fa-thumbs-down" aria-hidden="true"></i>
                <% end %><%= @recipe.thumbs_down_total %>
              </div>
            </div>
        </div>
      </div>
    </div>
</div>

<% if logged_in? %>
  <div class='container-fluid'>
    <div class='row justify-content-start'>
       <div class='w-100'>
        <%= form_for([@recipe, @comment], remote: true, :html => {class: 'form-group', role: 'form' }) do |f| %>
    <div class='form-group row'>
      <div class='form-control-label col-2 pl-5'>
        <%= f.label :description, "Comment" %>
      </div>
      <div class='col-10 pr-5'>
        <%= f.text_area :description, rows: 3, class: 'form-control border border-info', 
                             placeholder: 'Enter comment here', autofocus: true %>
      </div>
    </div>
    <div class='form-group'>
      <div class='col-2 pl-5'>
          <%= f.submit "Add Comment", class: 'btn btn-primary btn-sm btn-xlarge' %>
      </div>
    </div>
    <% end %>
  </div>
</div>
<% end %>

<% if @recipe.comments.any? %>
  <div class="row justify-content-center">
    <div class="col-8">
      <h3 class="text-center">Comments</h3>
      <div id="comments">
        <div id="messages">
          <%= render partial: 'comments/comments', object: @comments %>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class='row'>
    <div class='col-8'>
      <h5>No Comments Yet!</h5>
    </div>
  </div>
<% end %>