config/routes.rb
Rails.application.routes.draw do
  
  root "pages#home"
  get 'pages/home', to: 'pages#home'
   get '/about', to: 'pages#about'
   
   resources :recipes do
     resources :comments, only: [:create]
     member do
      post 'like'
     end
   end
   
   get'/signup', to: 'chefs#new'
   resources :chefs, except: [:new]
   
   get '/login', to: 'sessions#new'
   post '/login', to: "sessions#create"
   delete '/logout', to: "sessions#destroy"
   
   resources :ingredients, except: [:destroy]
   
    mount ActionCable.server => 'cable'
   
   get '/chat', to: 'chatrooms#show'
   
   resources :messages, only: [:create]
  
end

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class='container'>
  <div class='row'>
    <div class='col-10'>
      <div class='card text-danger border-danger mb-3'>
        <div class='card-heading'>
          <h2 class='card-title text-center'>
            <%= pluralize(obj.errors.count, 'error') %>
            prohibited this <%= obj.class %> from being saved:
          </h2>
          <div class='card-body'>
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="mt-4 fixed-bottom">
    <div class="container-fluid py-3">
      <div class="row">
          <div class="col-8">
            <small>RecipeBox <em>by Rhonda Tinkham &copy;2017</em></small>
          </div>
          <div class="col-4 text-right small align-self-end">
            <%= link_to 'About', '/about' %>
          </div>
      </div>
    </div>
</footer>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light navbar-custom justify-content-start">
 
  <%= link_to 'RecipeBox', root_path, class: 'navar-brand pl-5 d-flex mr-auto', id: 'logo' %>
  
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav mx-auto w-100">
      <li class="nav-item">
        <%= link_to "Chefs", chefs_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Recipes", recipes_path, class: "nav-link" %>
      </li>
      <% if logged_in? %>
        <li class="nav-item">
        <%= link_to "ChefChat", chat_path, class: "nav-link" %>
      </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            CreateRecipes
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item">
              <%= link_to "Create a new recipe", new_recipe_path %>
            </a>
          </div>
        </li>
         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Ingredients
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item">
              <%= link_to "All Ingredients", ingredients_path %>
            </a>
            <% Ingredient.all.each do |ingredient| %>
              <a class="dropdown-item">
                <%= link_to ingredient.name.capitalize, ingredient_path(ingredient) %>
              </a>
            <% end %>
            <% if logged_in? && current_chef.admin? %>
              <div role="separator" class="dropdown-divider"></div>
                <a class="dropdown-item">
                  <%= link_to "New Ingredient", new_ingredient_path %>
                </a>
            <% end %>
          </div>
        </li>
      <% end %>
        <ul class="nav navbar-nav ml-auto w-50 justify-content-end">
      
        <% if logged_in? %>
        
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_chef.chefname.capitalize %>'s Profile
                 <%= "| Admin" if current_chef.admin? %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item">
              <%= link_to "View your profile", chef_path(current_chef) %>
            </a>
            <a class="dropdown-item">
              <%= link_to "Edit your profile", edit_chef_path(current_chef) %>
            </a>
            <div role="separator" class="dropdown-divider"></div>
            <a class="dropdown-item">
            <%= link_to "Log Out", logout_path, method: :delete %>
          </a>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log In", login_path, class: "nav-link" %>
          </li>
        <% end %>
     
      </ul>
    </ul>
  </div>
</nav>

app/views/shared/_page_title.html.erb
<h1 align="center"><%= title.titleize %></h1>