config/routes.rb
Rails.application.routes.draw do
  
  root "pages#home"
  get 'pages/home', to: 'pages#home'
   get '/about', to: 'pages#about'
   
   resources :recipes do
     resources :comments, only: [:create]
     member do
      post 'like'
     end
   end
   
   get'/signup', to: 'chefs#new'
   resources :chefs, except: [:new]
   
   get '/login', to: 'sessions#new'
   post '/login', to: "sessions#create"
   delete '/logout', to: "sessions#destroy"
   
   resources :ingredients, except: [:destroy]
   
    mount ActionCable.server => 'cable'
   
   get '/chat', to: 'chatrooms#show'
   
   resources :messages, only: [:create]
  
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:edit, :update, :show]
  before_action :require_admin, except: [:show, :index]
  
  def new
    @ingredient = Ingredient.new
  end
  
  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      flash[:warning] = "Ingredient was successfully created"
      redirect_to ingredient_path(@ingredient)
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @ingredient.update(ingredient_params)
      flash[:warning] = "Ingredient name was updated"
      redirect_to @ingredient
    else
      render 'edit'
    end
  end
  
  def show
    @ingredient_recipes = @ingredient.recipes.paginate(page: params[:page],
              per_page: 5)
  end
  
  def index 
    @ingredients = Ingredient.paginate(page: params[:page], per_page: 5)
  end
  
  private
  
  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
  
  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end
  
  def require_admin
    if !logged_in? || (logged_in? and !current_chef.admin?)
      flash[:danger] = "Only admin users can perform that action"
      redirect_to ingredients_path
    end
  end
  
end

app/views/ingredients/_form.html.erb
<%= render 'shared/errors', obj: @ingredient %>

<div class='container'>
<div class='row justify-content-start'>
   <div class='w-100'>
    <%= form_for(@ingredient, :html => {class: 'form-group', role: 'form' }) do |f| %>
    <div class='form-group row'>
      <div class='form-control-label col-2'>
        <%= f.label :name %>
      </div>
      <div class='col-10'>
        <%= f.text_field :name, class: 'form-control border border-info', 
                             placeholder: 'Enter ingredient', autofocus: true %>
      </div>
    </div>
    
    <div class='form-group'>
      <div class='col-2'>
          <%= f.submit(@ingredient.new_record? ? "Add Ingredient" : "Update Ingredient",
                 class: 'btn btn-primary btn-sm btn-xlarge') %>
      </div>
    </div>
    <% end %>
  </div>
</div>
    <div class='col-6 colormatch'>
      [<%= link_to 'Cancel', recipes_path %>]
    </div>
  </div>
</div>
</div>

app/views/ingredients/_ingredient.html.erb
<span class="badge badge-pill badge-light" id="ing-badge">
  <%= link_to ingredient.name, ingredient_path(ingredient) %>
</span>

app/views/ingredients/edit.html.erb
<%= render 'shared/page_title', title: "edit ingredient name" %>

<%= render 'form' %>

app/views/ingredients/index.html.erb
<%= render 'shared/page_title', title: "available ingredients" %>

<div class='container' align='center'>
  <div class="pagination justify-content-center apple_pagination">
    <%= will_paginate %>
  </div>
  <% @ingredients.each do |ing| %>
    <ul class='listing'>
      <div class='row'>
          <div class="col d-flex justify-content-center card border-info mb-3">
            <div class='justify-content-md-center card-body'>
              <li class="chef-title">
                <%= link_to ing.name.capitalize, ingredient_path(ing) %>
              </li>
              <li>
                <small>
                  <%= pluralize(ing.recipes.count, "recipe") if ing.recipes %>
                </small>
              </li>
              <li>
                <% if logged_in? and current_chef.admin? %>
                  <%= link_to "Edit this ingredient", edit_ingredient_path(ing) %>
                <% end %>
              </li>
            </div>
      </div>
    </ul>
  <% end %>
  <div class="pagination justify-content-center apple_pagination">
    <%= will_paginate %>
  </div>
</div>

app/views/ingredients/new.html.erb
<%= render 'shared/page_title', title: "enter a new ingredient" %>

<%= render 'form' %>

app/views/ingredients/show.html.erb
<%= render 'shared/page_title', title: "#{@ingredient.name.capitalize}" %>

    <div class='row'>
      <div class="col d-flex justify-content-center card mb-3">
          
        <div class='justify-content-md-center card-body colormatch'>
          <% if @ingredient.recipes.count != 0 %>
            <h4 class="center">Recipes's containing <%= @ingredient.name.capitalize %></h4>
            <div class="pagination justify-content-center apple_pagination">
              <%= will_paginate @ingredient_recipes %>
            </div>
            <%= render 'recipes/recipe', obj: @ingredient_recipes %>
            <div class="pagination justify-content-center apple_pagination">
              <%= will_paginate @ingredient_recipes %>
            </div>
          <% else %>
            <h4 class="center">No recipes yet!</h4>
          <% end %>
        </div>
      </div>
    </div>