config/routes.rb
Rails.application.routes.draw do
  
  root "pages#home"
  get 'pages/home', to: 'pages#home'
   get '/about', to: 'pages#about'
   
   resources :recipes do
     resources :comments, only: [:create]
     member do
      post 'like'
     end
   end
   
   get'/signup', to: 'chefs#new'
   resources :chefs, except: [:new]
   
   get '/login', to: 'sessions#new'
   post '/login', to: "sessions#create"
   delete '/logout', to: "sessions#destroy"
   
   resources :ingredients, except: [:destroy]
   
    mount ActionCable.server => 'cable'
   
   get '/chat', to: 'chatrooms#show'
   
   resources :messages, only: [:create]
  
end

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/home.html.erb
<div class="card bg-light" id='cardHome'>
  <img class="card-img" alt="">
  <div class="card-img-overlay">
    <div class="card-body text-white">
      <h2 class="card-title h2Home">Welcome to Rhonda's RecipesBox</h2>
    </div>
  </div>
</div>

<div class='container'>
  <div class="row">
    <div class="col-4">
      <h2>View Recipes</h2>
      <p>Browse the recipes for free, and sign up for an account later.</p>
      <p><%= link_to 'View all Recipes »', recipes_path, class: 'btn btn-light btn-xlarge' %></p>
    </div>
    <div class="col-4">
      <h2>Log In</h2>
      <p>Add and update your own recipes. Vote for favourite recipes. Write reviews, and more.</p>
        <p><%= link_to 'Log In »', 'login_path', class: 'btn btn-light btn-xlarge' %></p>
    </div>
    <div class="col-4">
      <h2>Sign Up</h2>
      <p>Get access to add your own recipes, write reviews, and vote for your favourite recipes.</p>
        <p><%= link_to 'Sign Up! :) »', signup_path, class: 'btn btn-light btn-xlarge' %></p>
    </div>
  </div>
</div>

<!--<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">-->
<!--  <ol class="carousel-indicators">-->
<!--    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>-->
<!--    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>-->
<!--    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>-->
<!--  </ol>-->
<!--  <div class="carousel-inner">-->
<!--    <div class="carousel-item active">-->
<!--      <img class="d-block w-100 first-slide" src="" alt="First slide">-->
<!--    </div>-->
<!--    <div class="carousel-item">-->
<!--      <img class="d-block w-100 second-slide" src="..." alt="Second slide">-->
<!--    </div>-->
<!--    <div class="carousel-item">-->
<!--      <img class="d-block w-100 third-slide" src="..." alt="Third slide">-->
<!--    </div>-->
<!--  </div>-->
<!--  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">-->
<!--    <span class="carousel-control-prev-icon" aria-hidden="true"></span>-->
<!--    <span class="sr-only">Previous</span>-->
<!--  </a>-->
<!--  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">-->
<!--    <span class="carousel-control-next-icon" aria-hidden="true"></span>-->
<!--    <span class="sr-only">Next</span>-->
<!--  </a>-->
<!--</div>-->